version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - doxygen
    - cmake
  jobs:
    pre_build:
      - cmake -S . -B build -DPOET_GENERATE_DOCS=ON
      - cmake --build build --target doxygen -- -j 2

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
