include_guard(GLOBAL)

option(POET_ENABLE_CLANG_TIDY "Enable clang-tidy diagnostics" OFF)
option(POET_CLANG_TIDY_CHECKS "Override clang-tidy checks" "")
option(POET_ENABLE_CPPCHECK "Enable cppcheck diagnostics" OFF)
option(POET_CPPCHECK_OPTIONS "Additional cppcheck options" "--enable=warning,style,performance,portability")

function(poet_configure_static_analysis target)
  if(NOT TARGET "${target}")
    message(FATAL_ERROR "poet_configure_static_analysis called with non-existent target '${target}'")
  endif()

  if(POET_ENABLE_CLANG_TIDY)
    find_program(_clang_tidy_exe NAMES clang-tidy clang-tidy-17 clang-tidy-16)
    if(_clang_tidy_exe)
      if(POET_CLANG_TIDY_CHECKS)
        set(_clang_tidy_command "${_clang_tidy_exe};-checks=${POET_CLANG_TIDY_CHECKS};-warnings-as-errors=*")
      else()
        set(_clang_tidy_command "${_clang_tidy_exe};-warnings-as-errors=*")
      endif()
      set_property(TARGET ${target} PROPERTY CXX_CLANG_TIDY "${_clang_tidy_command}")
    else()
      message(WARNING "POET_ENABLE_CLANG_TIDY is ON but clang-tidy was not found on PATH")
    endif()
  endif()

  if(POET_ENABLE_CPPCHECK)
    find_program(_cppcheck_exe NAMES cppcheck)
    if(_cppcheck_exe)
      set(_cppcheck_command "${_cppcheck_exe};${POET_CPPCHECK_OPTIONS}")
      set_property(TARGET ${target} PROPERTY CXX_CPPCHECK "${_cppcheck_command}")
    else()
      message(WARNING "POET_ENABLE_CPPCHECK is ON but cppcheck was not found on PATH")
    endif()
  endif()
endfunction()
